---
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.Date={{.CommitDate}}
    mod_timestamp: '{{.CommitTimestamp}}'
archives:
  - formats:
      - binary
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto

dockers_v2:
  - images:
      - 'arnested/{{ .ProjectName }}'
    tags:
      - '{{ .Tag }}'
      - 'v{{ .Major }}'
      - 'latest'
    sbom: true
    labels:
      "org.opencontainers.image.created": "{{.CommitDate}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.source": "https://github.com/arnested/{{.ProjectName}}"
      "org.opencontainers.image.title": "systemd state http server"
      "org.opencontainers.image.description": "A small HTTP server exposing the overall state of systemd"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.licenses": "MIT"
      "org.opencontainers.image.authors": "Arne Jørgensen <arne@arnested.dk>"

nfpms:
  -
    vendor: Arne Jørgensen
    maintainer: Arne Jørgensen <arne@arnested.dk>
    description: http server for monitoring systemd state
    license: MIT
    formats:
      - deb
    dependencies:
      - libsystemd0
    bindir: /usr/libexec
    changelog: ./changelog.yml
    contents:
      - src: systemd/systemd-state.service
        dst: /lib/systemd/system/systemd-state.service

      - src: deb/systemd-state.sources
        dst: /etc/apt/sources.list.d/systemd-state.sources

      - src: deb/systemd-state.gpg
        dst: /usr/share/keyrings/systemd-state.gpg

    scripts:
      postinstall: "deb/postinstall.sh"
      preremove: "deb/preremove.sh"
      postremove: "deb/postremove.sh"

    deb:
      triggers:
        interest_noawait:
          - /lib/systemd/systemd
