before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto

nfpms:
  -
    vendor: Arne Jørgensen
    maintainer: Arne Jørgensen <arne@arnested.dk>
    description: http server for monitoring systemd state
    license: MIT
    formats:
      - deb
    dependencies:
      - libsystemd0
    bindir: /usr/libexec
    contents:
      - src: systemd/systemd-state.service
        dst: /lib/systemd/system/systemd-state.service

      - src: deb/systemd-state.sources
        dst: /etc/apt/sources.list.d/systemd-state.sources

      - src: deb/systemd-state.gpg
        dst: /usr/share/keyrings/systemd-state.gpg

    scripts:
      postinstall: "deb/postinstall.sh"
      preremove: "deb/preremove.sh"
      postremove: "deb/postremove.sh"

    deb:
      triggers:
        interest_noawait:
          - /lib/systemd/systemd
