dist: xenial

language: go

go:
  - '1.14'

env:
  global:
    - GO111MODULE=on

before_install:
  - GO111MODULE=off go get github.com/mitchellh/gox
  - GO111MODULE=off go get github.com/frapposelli/wwhrd
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -v -race -coverprofile=c.out -covermode=atomic ./...
  - go mod vendor && wwhrd check

after_script:
  - rm -rf vendor
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - gox -os=linux -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
