dist: xenial

language: go

go:
  - '1.14'

env:
  global:
    - GO111MODULE=on

before_install:
  - GO111MODULE=off go get github.com/mitchellh/gox
  - GO111MODULE=off go get github.com/frapposelli/wwhrd
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -v -race -coverprofile=c.out -covermode=atomic ./...
  - go mod vendor && wwhrd check

after_script:
  - rm -rf vendor
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - gox -os=linux -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"

deploy:
  # Deploy to Github Releases
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: l2wSOjuW767zqUX+wNQHGSISUybdemfXSWO38XknJJ90CbeJUrQZyePc80XSK6hgBhfwF0IbdWLUhJYBvI4YXQt/gENrI1MlhnWVtiqNZMpSTr3Y+/gwuDMXH94WOGh8VdvL2MSE2B+OoHiYGvyGmWJPnHFD2Sqja/wZP7WThrreZJUj/7wJgmEkj4dl9DM3c5xNW1LMHR9hR3/w4aSt1z66LXbPa6Pvf59zod9QvMh2CKJYTK+y3pzP0ZS8SPTCwzOZ26wrLTE6qJWfqIEKytP+VTkByTH90MLiOxmof+DQHrv9y/hJdKEBQS7+bqeROr1WjrgHkBD/6YTj53xuC/1+pt+xCepS5SUPcUIZjNrtrdnQx3pdwnqIBrU8Y3WwWa/PlmCpkAwWCt4W4k0ehXhCSAEfqOwKUZzkGOi2dDLw6Y5tUwS6E1kKS26n1bgu1SvKTqlmgCNyrUFyeuX/nhHUpr7nrkznaPp6AKCpMSb98lUh9fJ8XbRjrBky2HJwtBX44al8kvJDOoTQBka8xpCyeNc0qW6J72xB3v0MPkEXmDEqyO68Cq1BiHrj9iIFEQBPrXn4yofeQvC+Pz6pYZbP9LsOg0K5Co1mjQNGtLsm6TeRr/l3Orjwrc/j3sE12gYUGz+Atf180dQwMBGxf7WGijjfjTIs2Jmy4ul41w0=
    file_glob: true
    file: dist/*
    on:
      repo: arnested/systemd-state
      tags: true

  # Purge the releases badge to get the new release number in there
  - provider: script
    script: curl --silent -X PURGE https://camo.githubusercontent.com/7ada60ab70c16db616686cda4aed0ae188ecb7ae/68747470733a2f2f6769746875622d72656c656173652d76657273696f6e2e6865726f6b756170702e636f6d2f6769746875622f61726e65737465642f73797374656d642d73746174652f72656c656173652e737667
    on:
      repo: arnested/systemd-state
      tags: true

  # Refresh goreportcard.com report
  - provider: script
    script: 'curl --silent -X POST -H "Content-Type: application/x-www-form-urlencoded" https://goreportcard.com/checks --data "repo=github.com%2Farnested%2Fsystemd-state"'
    on:
      repo: arnested/systemd-state
      branch: master

  # Refresh godoc.org documentation
  - provider: script
    script: 'curl --silent -X POST -H "Content-Type: application/x-www-form-urlencoded" https://godoc.org/-/refresh --data "path=github.com%2Farnested%2Fsystemd-state"'
    on:
      repo: arnested/systemd-state
      branch: master
