on: push
name: Docker build and push
jobs:
  build:
    name: Docker build and push
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        # Assume the same repo name on Docker Hub as on GitHub
        repository: ${{ github.repository }}
        tag_with_ref: true
        add_git_labels: true
    - name: Push README to Docker Hub
      if: github.ref == 'refs/heads/master' && !github.event.deleted
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_TOKEN }}
      with:
        destination_container_repo: ${{ github.repository }}
