on: push
name: Docker image security scan
permissions:
  security-events: write
  actions: read
jobs:
  security-scan:
    name: Docker build and scan
    if: '!github.event.deleted'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        builder: ${{ steps.buildx.outputs.name }}
        tags: ${{ github.repository }}:test
        push: false
        load: true
    - name: Scan Docker image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: ${{ github.repository }}:test
        acs-report-enable: true
        fail-build: true
    - name: Upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      if: ${{ always() }}
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
