on: push
name: Docker build
jobs:
  build:
    name: Docker build
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker build
      run: docker build .
